# Generated by Django 5.2.12 on 2026-04-25 00:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre')),
                ('country', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='País')),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('address', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Dirección')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='residential.condominium', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'Fondo',
                'verbose_name_plural': 'Fondos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundSummaryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Resumen de aportes',
                'verbose_name_plural': 'Resumen de aportes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('residential.fund',),
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, verbose_name='Identificador')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Nombre del Propietario')),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='residential.condominium')),
            ],
            options={
                'verbose_name': 'Residencia',
                'verbose_name_plural': 'Residencias',
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='residential.fund', verbose_name='Fondo')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='residence',
            constraint=models.UniqueConstraint(fields=('condominium', 'identifier'), name='unique_residence_identifier'),
        ),
    ]
