# Generated by Django 5.2.12 on 2026-03-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='residential.condominium', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'Fondo',
                'verbose_name_plural': 'Fondos',
                'ordering': ['-created_at'],
            },
        ),
    ]
