# Generated by Django 5.2.12 on 2026-05-13 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Desembolso')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='residential.fund', verbose_name='Fondo')),
            ],
            options={
                'verbose_name': 'Desembolso',
                'verbose_name_plural': 'Desembolsos',
                'ordering': ['-created_at'],
            },
        ),
    ]
