# Generated by Django 5.2.12 on 2026-05-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_disbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.TextField(default=1, verbose_name='Nota'),
            preserve_default=False,
        ),
    ]
