# Generated by Django 5.2.12 on 2026-03-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
