# Generated by Django 5.2.12 on 2026-04-16 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_alter_condominium_city_alter_condominium_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominium',
            name='address',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='city',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominium',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre'),
        ),
    ]
