# Generated by Django 5.2.12 on 2026-04-16 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0003_alter_condominium_address_alter_condominium_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominium',
            name='country',
            field=models.CharField(default=1, max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='País'),
            preserve_default=False,
        ),
    ]
