# Generated by Django 5.2.12 on 2026-03-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0003_alter_fund_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='residential.fund', verbose_name='Fondo')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='residential.residence', verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
