# Generated by Django 5.2.12 on 2026-03-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominium',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal'),
        ),
    ]
