# Generated by Django 5.2.12 on 2026-03-26 22:01

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0005_alter_condominium_city_alter_condominium_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='residence',
        ),
        migrations.AddField(
            model_name='payment',
            name='Residence',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fund', chained_model_field='condominium', default=1, on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia'),
            preserve_default=False,
        ),
    ]
