# Generated by Django 5.2.12 on 2026-03-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0006_remove_payment_residence_payment_residence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Residence',
            new_name='residence',
        ),
    ]
