# Generated by Django 5.2.12 on 2026-03-28 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0007_rename_residence_payment_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundSummaryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Resumen de aportes',
                'verbose_name_plural': 'Resumen de aportes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('residential.fund',),
        ),
    ]
